[font]
size = 12.0

[font.bold]
family = "Maple mono"
style = "Bold"

[font.italic]
family = "Maple mono"
style = "Italic"

[font.normal]
family = "Maple mono"
style = "Regular"

[window]
opacity = 0.5  # Adjust as needed (1.0 = Opaque, 0.0 = Fully Transparent)


